# Generated by Django 5.2.8 on 2025-12-02 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarpetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Gilam turi nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('price_per_m2', models.IntegerField(verbose_name='1 m² narxi (so`m)')),
            ],
            options={
                'verbose_name': 'Gilam turi',
                'verbose_name_plural': 'Gilam turlari',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Foydalanuvchi ismi')),
                ('message.css', models.TextField(verbose_name='Izoh matni')),
                ('rating', models.IntegerField(choices=[(1, '1 Yulduz'), (2, '2 Yulduz'), (3, '3 Yulduz'), (4, '4 Yulduz'), (5, '5 Yulduz')], verbose_name='Reyting')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yozilgan sana')),
            ],
            options={
                'verbose_name': 'Izoh',
                'verbose_name_plural': 'Izohlar',
            },
        ),
        migrations.CreateModel(
            name='VisitorCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Sana')),
                ('count', models.IntegerField(default=1, verbose_name='Kirishlar soni')),
            ],
            options={
                'verbose_name': 'Saytga kirishlar',
                'verbose_name_plural': 'Saytga kirishlar statistikasi',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism familiya')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('address', models.CharField(max_length=255, verbose_name='Manzil')),
                ('other_carpet_name', models.CharField(blank=True, help_text='Agar ro`yxatda bo`lmasa, o`zingiz gilam nomini kiriting', max_length=100, verbose_name='Boshqa gilam nomi')),
                ('date', models.DateField(verbose_name='Buyurtma kuni')),
                ('comment', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('carpet_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.carpettype', verbose_name='Gilam turi')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
            },
        ),
    ]
