# Generated by Django 5.2.4 on 2025-12-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('processing', 'Jarayonda'), ('completed', 'Tugatilgan')], default='new', max_length=20, verbose_name='Holat'),
        ),
    ]
