# Generated by Django 5.2.4 on 2025-12-02 16:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Telefon raqam quyidagi formatda bo'lishi kerak: +998901234567", regex='^\\+998\\d{9}$')], verbose_name='Telefon raqam'),
        ),
    ]
