# Generated by Django 5.2.4 on 2025-12-02 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_order_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='VisitorCount',
        ),
    ]
