# Generated by Django 5.2.4 on 2025-12-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_sitevisit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitevisit',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='session_key',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
