# Generated by Django 5.2.4 on 2025-12-04 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_timestamp_sitevisit_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='SiteVisit',
        ),
        migrations.AddIndex(
            model_name='visitlog',
            index=models.Index(fields=['user', 'timestamp'], name='app_visitlo_user_id_41d3c5_idx'),
        ),
        migrations.AddIndex(
            model_name='visitlog',
            index=models.Index(fields=['timestamp'], name='app_visitlo_timesta_c545f1_idx'),
        ),
        migrations.AddIndex(
            model_name='visitlog',
            index=models.Index(fields=['session_key'], name='app_visitlo_session_50e0ad_idx'),
        ),
    ]
